# Generated by Django 4.1.7 on 2023-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime_Collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeDetailedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('anime_name', models.CharField(max_length=256)),
                ('episode_num', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('collection_type', models.CharField(max_length=256)),
                ('rating', models.CharField(max_length=256)),
                ('comment', models.TextField()),
            ],
        ),
    ]
