# Generated by Django 4.1.7 on 2023-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime_Collection', '0002_animedetaileddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendDataFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushed', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=256)),
                ('friend_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('friend_id', models.CharField(max_length=256)),
            ],
        ),
    ]
