# Generated by Django 4.1.7 on 2023-03-12 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsrv', '0005_userinfo_usrverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='reg_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
