# Generated by Django 4.1.7 on 2023-03-16 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsrv', '0006_userinfo_reg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_online',
            field=models.CharField(default='False', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='online_client_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
