# Generated by Django 4.1.7 on 2023-03-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsrv', '0007_userinfo_is_online_userinfo_online_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.TextField(),
        ),
    ]
