# Generated by Django 4.1.7 on 2023-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('client_secret', models.CharField(max_length=256)),
                ('authed_uid', models.CharField(max_length=256)),
                ('auth_code', models.CharField(max_length=256)),
                ('auth_code_expired', models.CharField(max_length=256)),
                ('access_token_key', models.CharField(max_length=256)),
            ],
        ),
    ]
