# Generated by Django 4.1.7 on 2023-03-12 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OAuthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtable',
            name='sitename',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
